### PR TITLE
Add ability to collapse tickets, and add a setting to auto-collapse a given ticket upon page load

### PR DESCRIPTION
**Pull request by grablair**
The use case here is for events with large numbers of tiered tickets. In my case, I have an event with 11 tiered tickets, each with 3+ tiers, and each tiered ticket corresponds to a given day.

In this case, the page is very long/noisy, and hard to navigate. Auto-collapsing the tickets so that the user only sees all the dates, initially, should help increase user-friendliness for these types of events.

I think it may be worth considering auto-collapsing all tickets by default if there are more than a certain amount of tickets on the page. This change does not do that, though; all tickets are not collapsed by default.

Screenshot 2024-10-14 at 15 44 01
Screenshot 2024-10-14 at 15 44 24

## Checklist

- [X] I have read the contributing guidelines.
- [X] My code is of good quality and follows the coding standards of the project.
- [X] I have tested my changes, and they work as expected.

Thank you for your contribution! 🎉

### CODE REVIEW

**Comment by grablair** [comment]
Added logic to make remaining ticket count work w/ the collapse arrow:

Screenshot 2024-10-14 at 16 01 52

**Comment by daveearley** [comment]
I like this! Thanks for adding it. I'll set aside some time to test it soon.

**Comment by grablair** [comment]
Screenshot 2024-10-15 at 08 38 44

Changed the "closed" arrow to a right-facing arrow, implying that when you click on it, there will be a next step.

**Comment by daveearley** [comment]
Tested and working great. Thanks again @grablair. Very much appreciated!

**Pull request merged**
