### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by zarevskaya**
update, on the road again.

### CODE REVIEW

**Comment by zarevskaya** [comment]
Update!

**Comment by zarevskaya** [comment]
Test sign

**Comment by zarevskaya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by daveearley** [comment]
Thanks @zarevskaya! I've updated the target branch to `i18n`, that's where I'm [working on internationalisation](https://github.com/HiEventsDev/hi.events/pull/50).

**Pull request merged**
